# Generated by Django 4.0.4 on 2022-10-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='raiting',
        ),
    ]
