# Generated by Django 4.0.4 on 2022-11-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_review_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rating',
            new_name='raiting',
        ),
    ]
